### ISSUE TITLE
Any plans to port to 1.19?

### ISSUE THREAD

**Issue by TalEdd** [PieKing1215/DripSounds#8]
Would appreciate it, greatly!😊

**Comment by PieKing1215** [comment]
Yep, will come next after I finish the [InvMove update](https://github.com/PieKing1215/InvMove/issues/12).
I was already working on some big internal changes for InvMove when 1.19 came out which is why it's taking so long to finish.
For DripSounds I'm going to wait until after I port it to 1.19 to do similar internal changes so it should be quicker.

**Comment by ghost** [comment]
Hello, I would love to use that mod on 1.19! 
Greetings ❤️

**Comment by ghost** [comment]
Thank you for the super fast update! Works flawless on 1.19, this can be closed 🥰

**Comment by PieKing1215** [comment]
That's good to hear! Not sure I would call it a "super fast" update but I'm glad I finally got around to it.
Next step is to combine the Fabric/Forge versions (like I did with InvMove) which should help make future updates faster
